from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .forms import StyledAuthenticationForm
from .views import (
    AccessDeniedView,
    DashboardView,
    DailySettlementView,
    ExpenseCategoryListView,
    ExpenseCreateView,
    ExpenseListView,
    ExpensePurposeCreateView,
    HomeRedirectView,
    IncomeCreateView,
    IncomeDeleteView,
    IncomeListView,
    IncomePurposeCreateView,
    IncomeUpdateView,
    PurchaseCreateView,
    PurchaseDetailView,
    PurchaseInvoiceDownloadView,
    PurchaseListView,
    PurchasePaymentCreateView,
    PurchasePaymentUpdateView,
    PermissionSettingsView,
    ReconciliationSummaryView,
    ReconciliationView,
    ReportsView,
    SalesListView,
    SupplierActiveView,
    SupplierCreateView,
    SupplierInactiveView,
    SupplierListView,
    SupplierUpdateView,
    UserCreateView,
    UserInactiveView,
    UserListView,
    UserUpdateView,
)

urlpatterns = [
    path("", HomeRedirectView.as_view(), name="home"),
    path(
        "login/",
        LoginView.as_view(
            template_name="auth/login.html",
            authentication_form=StyledAuthenticationForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("access-denied/", AccessDeniedView.as_view(), name="access-denied"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("sales/", SalesListView.as_view(), name="sales-list"),
    path("income/", IncomeListView.as_view(), name="income-list"),
    path("income/add/", IncomeCreateView.as_view(), name="income-add"),
    path("income/<int:pk>/edit/", IncomeUpdateView.as_view(), name="income-edit"),
    path("income/<int:pk>/delete/", IncomeDeleteView.as_view(), name="income-delete"),
    path("income/purposes/", IncomePurposeCreateView.as_view(), name="income-purpose-create"),
    path("purchases/", PurchaseListView.as_view(), name="purchase-list"),
    path("purchases/add/", PurchaseCreateView.as_view(), name="purchase-add"),
    path("purchases/<int:pk>/details/", PurchaseDetailView.as_view(), name="purchase-detail"),
    path("purchases/<int:pk>/invoice/", PurchaseInvoiceDownloadView.as_view(), name="purchase-invoice"),
    path("purchases/<int:pk>/pay/", PurchasePaymentCreateView.as_view(), name="purchase-pay"),
    path("purchases/payments/<int:pk>/edit/", PurchasePaymentUpdateView.as_view(), name="purchase-payment-edit"),
    path("suppliers/", SupplierListView.as_view(), name="supplier-list"),
    path("suppliers/add/", SupplierCreateView.as_view(), name="supplier-add"),
    path("suppliers/<int:pk>/edit/", SupplierUpdateView.as_view(), name="supplier-edit"),
    path("suppliers/<int:pk>/active/", SupplierActiveView.as_view(), name="supplier-active"),
    path("suppliers/<int:pk>/inactive/", SupplierInactiveView.as_view(), name="supplier-inactive"),
    path("users/", UserListView.as_view(), name="user-list"),
    path("users/permissions/", PermissionSettingsView.as_view(), name="permission-settings"),
    path("users/add/", UserCreateView.as_view(), name="user-add"),
    path("users/<int:pk>/edit/", UserUpdateView.as_view(), name="user-edit"),
    path("users/<int:pk>/inactive/", UserInactiveView.as_view(), name="user-inactive"),
    path("expenses/", ExpenseListView.as_view(), name="expense-list"),
    path("expenses/add/", ExpenseCreateView.as_view(), name="expense-add"),
    path("expenses/categories/", ExpenseCategoryListView.as_view(), name="expense-category-list"),
    path("expenses/purposes/", ExpensePurposeCreateView.as_view(), name="expense-purpose-create"),
    path("expenses/settlement/", DailySettlementView.as_view(), name="daily-settlement"),
    path(
        "reports/reconciliation/summary/",
        ReconciliationSummaryView.as_view(),
        name="reconciliation-summary",
    ),
    path("reports/reconciliation/", ReconciliationView.as_view(), name="reconciliation"),
    path("reports/", ReportsView.as_view(), name="reports"),
]
