# Generated by Django 5.2.4 on 2026-03-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_supplier_expenserecord_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='vendor',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
