# Generated by Django 5.2.4 on 2026-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_supplier_account_number_supplier_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='source_reference',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
