# Generated by Django 5.2.4 on 2026-03-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_expenserecord_source_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='source_supplier_no',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
