# Generated by Django 5.2.4 on 2026-03-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_supplier_source_supplier_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerecord',
            name='source_reference',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
