# Generated by Django 5.2.4 on 2026-03-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_purchaserecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaserecord",
            old_name="received_amount",
            new_name="paid_amount",
        ),
    ]
