# Generated by Django 5.2.4 on 2026-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_rename_purchase_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='attachment',
            field=models.FileField(blank=True, upload_to='purchase_files/'),
        ),
        migrations.AddField(
            model_name='purchaserecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
