# Generated by Django 5.2.4 on 2026-03-12 06:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_purchasepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gpay_settled', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_settled', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_settled_to', models.CharField(blank=True, max_length=120)),
                ('expense_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_cash_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-settlement_date', '-updated_at', '-pk'],
                'unique_together': {('user', 'settlement_date')},
            },
        ),
    ]
