# Generated by Django 5.2.4 on 2026-03-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_dailycashsettlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLedgerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_sale_no', models.IntegerField(unique=True)),
                ('bill_no', models.CharField(db_index=True, max_length=60)),
                ('sale_date', models.DateField(blank=True, db_index=True, null=True)),
                ('customer_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Credit', 'Credit'), ('Unknown', 'Unknown')], db_index=True, default='Unknown', max_length=20)),
                ('source_card_no', models.CharField(blank=True, max_length=120)),
                ('is_cancelled', models.BooleanField(db_index=True, default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sale_date', '-source_sale_no'],
                'indexes': [models.Index(fields=['sale_date', 'bill_no'], name='tracker_sal_sale_da_d5dedc_idx'), models.Index(fields=['customer_name', 'payment_mode'], name='tracker_sal_custome_006ca7_idx')],
            },
        ),
    ]
