# Generated by Django 5.2.4 on 2026-03-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_salesledgerrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesledgerrecord',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesledgerrecord',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesledgerrecord',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
