# Generated by Django 5.2.4 on 2026-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_salesledgerrecord_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesledgerrecord',
            name='split_card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='salesledgerrecord',
            name='split_cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
