# Generated by Django 5.2.4 on 2026-03-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_salesledgerrecord_split_card_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycashsettlement',
            name='cash_denominations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
