# Generated by Django 5.2.4 on 2026-03-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_expensecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycashsettlement',
            name='cash_denomination_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailycashsettlement',
            name='cash_difference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailycashsettlement',
            name='cash_in_hand',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
