# Generated by Django 5.2.4 on 2026-03-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_dailycashsettlement_cash_denomination_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_dashboard', models.BooleanField(default=True)),
                ('allow_sales', models.BooleanField(default=True)),
                ('allow_daily_settlement', models.BooleanField(default=True)),
                ('allow_income', models.BooleanField(default=True)),
                ('allow_purchases', models.BooleanField(default=True)),
                ('allow_suppliers', models.BooleanField(default=True)),
                ('allow_expenses', models.BooleanField(default=True)),
                ('allow_reports', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
