# Generated by Django 5.2.4 on 2026-03-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_reconciliationexpenseentry_reconciliationincomeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationincomeentry',
            name='opening_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
