# Generated by Django 5.2.4 on 2026-03-20 16:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0022_reconciliationincomeentry_opening_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationOpeningBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance_date",
                    models.DateField(
                        db_index=True,
                        default=datetime.date.today,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliation_opening_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reconciliation Opening Balance",
                "verbose_name_plural": "Reconciliation Opening Balances",
                "ordering": ["-balance_date", "-updated_at", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="reconciliationopeningbalance",
            constraint=models.UniqueConstraint(
                fields=("user", "balance_date"),
                name="unique_reconciliation_opening_balance_per_user_date",
            ),
        ),
    ]
